[package]
name = "git-plus"
version = "0.1.0"
edition = "2021"

[dependencies]
# Open in the default browser
open = "3.0.3"

# Use git command
git2 = "0.15.0"

# CLI parser
structopt = { version = "0.3", default-features = false }
